### ISSUE TITLE
omnetpp  command issue

### ISSUE THREAD

**Issue by Maldarowbi** [mmodenesi/omnetpy#2]
When trying to run this command "omnetpp" I received this message 
An error has occurred. See the log file
/home/userpp/omnetpp-6.0pre8/ide/configuration/1604266297856.log.
![omnetpp_error](https://user-images.githubusercontent.com/17973490/97817597-ceb95000-1c73-11eb-82ea-f552812db761.png)

**Comment by mmodenesi** [comment]
Could you please share the contents of the error log?

If you lost the container, spin off another one and if the same error pops up, share the result of

`cat <the path to the log>`

Thank you

**Comment by Maldarowbi** [comment]
> Could you please share the contents of the error log?
> 
> If you lost the container, spin off another one and if the same error pops up, share the result of
> 
> `cat <the path to the log>`
> 
> Thank you

![omnetpp](https://user-images.githubusercontent.com/17973490/98284755-f829f280-1f77-11eb-8026-af26f5e4b916.PNG)

**Comment by mmodenesi** [comment]
Thank you for the update. To me it is really difficult to debug the situation because I can not reproduce it in any way. This has to do most likely with the docker container not being able to use the x11 socket to launch graphical environment windows on your host machine.

If you are interested, check out this material http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/

That's where I got the recipe for launching omnetpp editor from within the container.

I would like to hear how that experience goes!

**Comment by mmodenesi** [comment]
Just to gather more info:
- are your running docker on windows?
- on ubuntu on a VirtualBox machine?

how is your setup?

**Comment by Maldarowbi** [comment]
> Thank you for the update. To me it is really difficult to debug the situation because I can not reproduce it in any way. This has to do most likely with the docker container not being able to use the x11 socket to launch graphical environment windows on your host machine.
> 
> If you are interested, check out this material http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
> 
> That's where I got the recipe for launching omnetpp editor from within the container.
> 
> I would like to hear how that experience goes!

Thanks for your reply.  I will give it a try and I will let you know.

**Comment by Maldarowbi** [comment]
> Just to gather more info:
> 
> * are your running docker on windows?
> * on ubuntu on a VirtualBox machine?
> 
> how is your setup?

I have used two options. Running the docker on windows,  and running the docker on Ubuntu ( actual machine not VM)

I received the same error in both of them.

I will try tomorrow to follow the link that you sent me and let you know.

Best regards,

**Comment by mmodenesi** [comment]
@Maldarowbi hi! any news regarding this issue?

**Comment by Maldarowbi** [comment]
> @Maldarowbi hi! any news regarding this issue?

It doesn't work; therefore, I switched to the C++ version.

**Comment by mmodenesi** [comment]
@Maldarowbi recently a friend of mine came accross a very similar situation and the workarround was to put

```
ForwardX11 yes
```

at the file `~/.ssh/config.`

Not entirely sure it would help in your case, but I would be very grateful if you could give it a try,

Thanks

**Comment by mmodenesi** [comment]
Feel free to reopen the issue with more info.
