### ISSUE TITLE
omnetpy issue when compiling with makefile

### ISSUE THREAD

**Issue by YacineBelal** [mmodenesi/omnetpy#3]
When trying to build bindings with make i get the following errors ( could they be due to g++ version? )
![1](https://user-images.githubusercontent.com/35225624/108772135-e71fe400-755c-11eb-89f7-8a38f5255892.png)

thank you in advance for your help.

**Comment by YacineBelal** [comment]
SOLVED by downgrading to omnetpp 5.6.2.

**Comment by mmodenesi** [comment]
Again, missed the notification of this issue, good to know you solved it yourself.

Are you building the images yourself?

Take a look at https://hub.docker.com/r/mmodenesi/omnetpy/tags
