### ISSUE TITLE
Unable to cast Python instance to C++ type error

### ISSUE THREAD

**Issue by YacineBelal** [mmodenesi/omnetpy#4]
After launching the pytictoc example i get the following message on the ide and a segmentation error on command line and debug mode is not working. any idea to why is this happening? thank you.
![1](https://user-images.githubusercontent.com/35225624/109095051-4e839280-771b-11eb-9c77-aa2aee1f8007.png)

**Comment by mmodenesi** [comment]
Hi, thank you for your interest on this project, could you provide a detailed list of steps to reproduce the issue?

what docker image are you using?

how are you launching the `pytictoc` example? is it the one that is part of this repository, or did you write it yourself following the getting started guide? if so, please share the code, too.

Sorry for the delayed answer, I missed the notification entirely.

**Comment by mmodenesi** [comment]
As mentioned in #3, using these https://hub.docker.com/r/mmodenesi/omnetpy/tags it just works (all the versions are ok).

**Comment by YacineBelal** [comment]
Hello! Thank you for your response and for this project, we wanted to develop keras models on omnet++ and your solution allows us to do just that.

This issue was actually solved ( i forgot to close it, my bad) by switching from pop os! to Ubuntu. can't see any other reason to this issue since i built the image the exact same way in both distros and it didn't work on pop os.

**Comment by mmodenesi** [comment]
Interesting, maybe I should consider pinning versions of packages. Thank you!
