### ISSUE TITLE
Non-Docker Installation

### ISSUE THREAD

**Issue by yasirroni** [mmodenesi/omnetpy#5]
Is it possible to use omnetpy without Docker?

In my case, the docker can't find OpenGL because I use NVidia (NVIDIA Corporation GK106 [GeForce GTX 660] (rev a1)) Driver in Ubuntu 20.04

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-userpp'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[osgEarth]* [Capabilities] Failed to create graphic window too.
Error: Unable to create OpenGL graphics context.
Loading OSG Viewer library... 
```

So, is it possible to use it outside the Docker (because the driver exist outside the Docker)?

_

ps: Or you are interested to solve OpenGL Issue?

**Comment by mmodenesi** [comment]
Everything that can be done in a container (docker or whatever containarization technology), can also be done in a non-containerized environment, provided that the correct configs, libs, runtimes, etc... are there.

I am sorry, but it is far outside my possibilities to provide non-docker instructions right now.

---

That said, maybe I can help you tuning the docker container creation to meet your needs.

To better understand your situation, do you **need** to use OSG to run simulations? or is this preventing your from running anything? For instance, can you launch pytictoc, pyrouting, or any other pysample?

See [this](https://github.com/mmodenesi/omnetpy/tree/master/advanced) for instructions on how to run a pysample.

**Comment by yasirroni** [comment]
I'm following the [pytictoc tutorial](https://github.com/mmodenesi/omnetpy/tree/master/getstarted) and it resulted in the same error:

```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-userpp'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

I'll keep try to find a proper NVidia Driver for the docker because I've not been able to install the driver inside docker.

_

Ps: how about make a Ubuntu 20.04 based image (because as far as I know, there is no problem with my graphic card with Ubuntu 20.04).

**Comment by mmodenesi** [comment]
I'll provide such an image in the next few days, I'll comment here.

**Comment by yasirroni** [comment]
Maybe, ubuntu 18 LTS would be easier as the base. It also supported by the original `doc/InstallGuide.pdf` installer tutorial.

**Comment by mmodenesi** [comment]
Take a look at https://hub.docker.com/repository/docker/mmodenesi/omnetpy

**Comment by mmodenesi** [comment]
If you use the image based on 20.04, take a look at this change https://github.com/mmodenesi/omnetpy/commit/326469a156eb5814bccc26d82e3933c7ecc32987

Let me know how this goes!

**Comment by yasirroni** [comment]
> I'm following the [pytictoc tutorial](https://github.com/mmodenesi/omnetpy/tree/master/getstarted) and it resulted in the same error:
> 
> ```
> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-userpp'
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast
> ```
> 
> I'll keep try to find a proper NVidia Driver for the docker because I've not been able to install the driver inside docker.
> 
> _
> 
> Ps: how about make a Ubuntu 20.04 based image (because as far as I know, there is no problem with my graphic card with Ubuntu 20.04).

Edit: I can run pytictoc simulation using your default Ubuntu 19 image, but the error persist. I just don't know that I need to start the simulation (yes it's throw error, but the simulations seems working seamlessly) . My bad.

**Comment by yasirroni** [comment]
> If you use the image based on 20.04, take a look at this change [326469a](https://github.com/mmodenesi/omnetpy/commit/326469a156eb5814bccc26d82e3933c7ecc32987)
> 
> Let me know how this goes!

I'll give an update next weekend if possible.

**Comment by mmodenesi** [comment]
Also, you may try something along this https://stackoverflow.com/questions/40092796/libgl-error-failed-to-load-driver-swrast-running-ubuntu-docker-container-on

**Comment by yasirroni** [comment]
> Take a look at https://hub.docker.com/repository/docker/mmodenesi/omnetpy

I'm trying [ub20.04_opp5.6.2](https://hub.docker.com/layers/mmodenesi/omnetpy/ub20.04_opp5.6.2/images/sha256-5f479b9180da5a51ec9e4db1f77537f3ef20efed9063d4d82406e22ebe4f5e42?context=explore). Can you share with us the `dockerfile` so that I can help debug and modify if necessary? Maybe make separate branch to this repo?

**Comment by mmodenesi** [comment]
https://github.com/mmodenesi/omnetpy/compare/from_ub20_04

**Comment by yasirroni** [comment]
Thank you, so far above problem is fixed, but the problem move to Omnet++. Moving to Omnet++ 6pre solve the issue on Ubuntu 20 (at least for my project that seems depend on Omnet++ 6pre.

**Comment by mmodenesi** [comment]
Great! I was trying to make ubuntu:20.04 and OMNeT++ 6pre{8,9,10} but I couldn't manage to compile correctly and the IDE was not available. Will take a closer look. Keep an eye on newer images on the dockerhub page.
