### ISSUE TITLE
Inheritance of C++ Object

### ISSUE THREAD

**Issue by yasirroni** [mmodenesi/omnetpy#7]
It seems that no inherintace is implemented in generating the binding? For example `cRectangleFigure` should inherit all functionality of `cAbstractShapeFigure`.

```
void bind_cRectangleFigure(pybind11::module &m)
{
    pybind11::class_<
        omnetpp::cRectangleFigure, omnetpp::cAbstractShapeFigure, omnetpp::cFigure,
        std::unique_ptr<omnetpp::cRectangleFigure, pybind11::nodelete>
        > py_cRectangleFigure(
        m,
        "_cRectangleFigure",
        R"docstring(
        A figure that displays a rectangle, with optionally rounded corners.

        As with all shape figures, drawing of both the outline and the fill
        are optional. Line and fill color, and several other properties are
        inherited from cAbstractShapeFigure.
        )docstring"
    );
```

I know that you mention on the README that bindings might be buggy and not all bindings are implemented. But, this one quite essentials, how to correct this behaviour of inheritance and how to manually and bindings from C++ funtion?

**Comment by mmodenesi** [comment]
Can you please provide a python example that doesn't work (this is: one that tries to access methods of cRectangle and fails)?

**Comment by yasirroni** [comment]
```
from pyopp import cRectangleFigure 

f = cRectangleFigure()
f.setFilled # this return error because it doesn't inherit cAbstractShapeFigure method

```

Here our fix:
https://github.com/nadfity/omnetpy/commit/d14d77aa50451846a8aa8967041f33aa07b88a1b
https://github.com/nadfity/omnetpy/commit/af71db397c88fa881210592c37cce07e364e8673
https://github.com/nadfity/omnetpy/commit/4cd226cc600ce88a835cd2ec01df466fcfd39a8f

Also,getSystemModule is missing, see our [fix](https://github.com/nadfity/omnetpy/commit/c0140c1c98bdf121709c4c27e80052d9b87574b8)

**Comment by mmodenesi** [comment]
That looks great! love to see this improving in other hands.

For context, the README warns about this :smile: :

> The python bindings were written as needed in order to port the OMNeT++ samples. Not 100% of the C++ APIs were ported (though it may be easy to include what is missing).
