### ISSUE TITLE
memory leaked problem

### ISSUE THREAD

**Issue by YacineBelal** [mmodenesi/omnetpy#8]
I would like to know if there's any C++ like mechanism of Cmessage deletion? i'm having a memory leaked problem because of the ever increasing quantity of messages.

i would gladly take any suggestion! thank you! :)

**Comment by mmodenesi** [comment]
Yes, try and delete the messages:

Example taken from [txc13.py](https://github.com/mmodenesi/omnetpy/blob/master/pysamples/pytictoc/txc13.py):

```python
    def handleMessage(self, ttmsg):
        assert isinstance(ttmsg, TicTocMsg13)

        if ttmsg.destination == self.getIndex():
            # Message arrived.
            EV << "Message " << ttmsg.getName() << " arrived after " << ttmsg.hopcount << " hops.\n"
            self.bubble("ARRIVED, starting new one!")
            self.delete(ttmsg)
```
