### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yasirroni** [mmodenesi/omnetpy#9]
Please add a formal [License](https://choosealicense.com/) that give user legal right to improve and use your code. Thank you.

**Comment by yasirroni** [comment]
[This is the license of omnetpp](https://github.com/omnetpp/omnetpp/blob/master/doc/License).

But your works is build on top, but separate from omnetpp.

**Comment by yasirroni** [comment]
Any update @mmodenesi?

**Comment by mmodenesi** [comment]
Your request is attendable, but currently I have no time to devote to this. This will be probably solved after july. Assume I will add the omnetpp licence. Sorry if this causes any inconvenience.

**Comment by mmodenesi** [comment]
Thanks for your patience, I'll be coming back to this in the next few weeks.

**Comment by mmodenesi** [comment]
Effectively, I think the most appropriate is to apply the ACADEMIC PUBLIC LICENCE https://github.com/omnetpp/omnetpp/blob/master/doc/License, which states:

> if you distribute verbatim or modified copies of this software, they must be distributed under this license.
